[mysql]
    # dsn连接信息
    dsn = "root:123456@tcp(127.0.0.1:3306)/game?charset=utf8mb4&parseTime=True&loc=Local"
    # 日志级别; silent | error | warn | info
    logLevel = "error"
    # 慢日志阈值;ms
    slowThreshold = 2000
    # 最大空闲连接数
    maxIdleConns = 50
    # 最大打开连接数
    maxOpenConns = 50
    # 连接最大存活时间
    connMaxLifetime = 3600